server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pot
    username: root
    password: 1234


  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secretKeyRT: mySuperSuperSecretKey
  expirationRT: 3600000

kurento:
  uri: ws://localhost:8888/kurento

janus:
  url: http://ec2-3-39-254-7.ap-northeast-2.compute.amazonaws.com:8088/janus

nginx:
  proxy-port: 8080

google:
  credentials:
    file:
      path: credentials.json
